# Generated by Django 2.2.4 on 2019-08-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
