# Generated by Django 2.2.4 on 2019-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190812_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
