# Generated by Django 2.2.4 on 2019-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190812_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Japan', max_length=80),
            preserve_default=False,
        ),
    ]
